In [1]:
import torch

In [2]:
N = 250
M = 1000
K = 5
p_prior = 0.1
p = 0.1
code = 0
steps = 1000

ps = '{:.3f}'.format(p).replace('.', '')
pps = '{:.3f}'.format(p_prior).replace('.', '')
Ns = str(N)
Ms = str(M)
Ks = str(K)
steps = str(steps)
code = str(code)

In [3]:
path_ = '/home/rodrigo/Dropbox/DOC/van_error_codes/models/_N_%s_M_%s_K_%s_p_prior_%s_steps_%s_code_%s/' % (Ns, Ms, Ks, pps, steps, code)

In [4]:
PATH = path_ + 'model_N_250_M_1000_K_5_p_0100_p_prior_0100_steps_1000/'

In [42]:
message = torch.load(PATH + 'message_N_%s_M_%s_K_%s_p_%s_p_prior_%s.pt' % (Ns, Ms, Ks, ps, pps))

In [43]:
message

tensor([[ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1., -1.,  ...,  1., -1.,  1.],
        [ 1.,  1., -1.,  ...,  1.,  1.,  1.],
        ...,
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.]])

In [44]:
decoding = torch.load(PATH + 'av_sample_N_%s_M_%s_K_%s_p_%s_p_prior_%s.pt' % (Ns, Ms, Ks, ps, pps))

In [45]:
decoding

tensor([[ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [-1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        ...,
        [-1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.]], requires_grad=True)

In [46]:
message[0]

tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
         1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  

In [47]:
decoding[0]

tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  

In [48]:
print(torch.sum(decoding[0]).item())
print(torch.sum(message[0]).item())

248.0
214.0


In [49]:
for j in range(message.shape[0]):
    print('-- Message #', j)
    print('Message # minus= ', N - torch.sum(message[j]).item())
    print('Decoded # minus= ', N - torch.sum(decoding[j]).item())

-- Message # 0
Message # minus=  36.0
Decoded # minus=  2.0
-- Message # 1
Message # minus=  66.0
Decoded # minus=  4.0
-- Message # 2
Message # minus=  44.0
Decoded # minus=  2.0
-- Message # 3
Message # minus=  80.0
Decoded # minus=  4.0
-- Message # 4
Message # minus=  42.0
Decoded # minus=  4.0
-- Message # 5
Message # minus=  72.0
Decoded # minus=  2.0
-- Message # 6
Message # minus=  40.0
Decoded # minus=  4.0
-- Message # 7
Message # minus=  48.0
Decoded # minus=  2.0
-- Message # 8
Message # minus=  50.0
Decoded # minus=  2.0
-- Message # 9
Message # minus=  54.0
Decoded # minus=  2.0
-- Message # 10
Message # minus=  64.0
Decoded # minus=  4.0
-- Message # 11
Message # minus=  42.0
Decoded # minus=  4.0
-- Message # 12
Message # minus=  34.0
Decoded # minus=  4.0
-- Message # 13
Message # minus=  58.0
Decoded # minus=  2.0
-- Message # 14
Message # minus=  56.0
Decoded # minus=  2.0
-- Message # 15
Message # minus=  38.0
Decoded # minus=  2.0
-- Message # 16
Message # minus=  